// pitchside-ai.js
//
// PitchSide AI: the per-video "tactical insight" popup (openAiInsight/
// closeAiInsight) and the Groq-powered chat assistant (sendAiMessage and
// its supporting UI). Split out of app.js (~12KB) so this only downloads
// for users who actually open an insight popup or the AI tab.
//
// LOADED VIA DYNAMIC import() FROM app.js — app.js stays a classic
// script (see match-detail.js's header comment for the full reasoning).
//
// UNLIKE war-room.js: every entry point here is reachable from STATIC
// onclick/onchange attributes already sitting in index.html (the AI tab
// under "More", and every video card's insight button) — not HTML this
// module generates itself. That means openAiInsight, closeAiInsight,
// sendAiMessage, aiTriggerFile, aiToggleAttachMenu, and
// aiHandleFileSelect all need PERMANENT STUBS in app.js (the
// match-detail.js pattern: exist synchronously from page load, delegate
// to this module once loaded) — direct window assignment from within
// this module (the war-room.js pattern) would be too late for these,
// since they can be clicked before this module has ever loaded.
// aiRemoveAttach is the one exception: it's only ever generated by this
// module's own renderAttachPreview, so by the time it could be clicked,
// this module is already loaded — direct assignment at the bottom of
// this file is fine for that one.
//
// escapeAttr (used to build the insight button's onclick string) is
// NOT moved here — it's shared with Post Creator's match-tagging
// elsewhere in app.js, and stays there as a plain function declaration
// (safe to reference as a bare identifier from this module, same
// class as _esc/showToast/normalizeLiveScoreStatus).
//
// Everything below is otherwise UNCHANGED from its original place in
// app.js — only `export` was added.

/* ── FEATURE 3: AI Insight panel logic ── */
export const _aiInsightCache = {}; // cache per videoId so we don't re-fetch

export async function openAiInsight(videoId, description) {
  const overlay = document.getElementById('ai-overlay-' + videoId);
  if (!overlay) return;
  overlay.classList.add('show');

  const textEl   = document.getElementById('ai-insight-text-' + videoId);
  const loaderEl = document.getElementById('ai-insight-loader-' + videoId);

  // Use cached result if available
  if (_aiInsightCache[videoId]) {
    if (loaderEl) loaderEl.style.display = 'none';
    textEl.innerHTML = _aiInsightCache[videoId];
    return;
  }

  // Show loader
  if (loaderEl) loaderEl.style.display = 'flex';

  try {
    const prompt = description
      ? `You are a sharp football analyst. Given this highlight description: "${description}" — provide a 3-sentence tactical insight about this football moment. Be specific, mention tactics/formations/player roles. Keep it concise and punchy.`
      : `You are a sharp football analyst. Give 3 punchy sentences of tactical analysis for a football highlight. Mention pressing, space creation, or finishing. Be specific and exciting.`;

    const res = await fetch('/api/ai', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        max_tokens: 200,
        messages: [{ role: 'user', content: prompt }]
      })
    });
    const data = await res.json();
    const reply = (data.content && data.content[0] && data.content[0].text) || 'No analysis available.';
    const html = reply.replace(/\n/g, '<br>');
    _aiInsightCache[videoId] = html;
    if (loaderEl) loaderEl.style.display = 'none';
    textEl.innerHTML = html;
  } catch(e) {
    if (loaderEl) loaderEl.style.display = 'none';
    textEl.textContent = '⚠️ Analysis unavailable. Check your connection.';
  }
}

export function closeAiInsight(videoId) {
  const overlay = document.getElementById('ai-overlay-' + videoId);
  if (overlay) overlay.classList.remove('show');
}
export function formatAiText(text) {
  return escHtml(text)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^• /gm, '&bull; ')
    .replace(/\n\n/g, '<br><br>')
    .replace(/\n/g, '<br>');
}

export function nowTime() {
  return new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'});
}

export function appendAiMessage(role, text, attachments) {
  const body   = document.getElementById('ai-chat-body');
  const isBot  = role === 'bot' || role === 'assistant';
  const initials = (typeof profileData !== 'undefined' && profileData) ? profileData.initials : 'ME';
  const bubble = document.createElement('div');
  bubble.className = `ai-bubble ${isBot ? 'ai-bubble-bot' : 'ai-bubble-user'}`;

  let mediaHtml = '';
  if (attachments && attachments.length > 0) {
    attachments.forEach(a => {
      if (a.type === 'photo') {
        mediaHtml += `<div class="ai-media-preview"><img src="${a.dataUrl}" alt="photo"></div>`;
      } else if (a.type === 'video') {
        mediaHtml += `<div class="ai-media-preview"><video src="${a.dataUrl}" controls playsinline></video></div>`;
      } else {
        mediaHtml += `<div class="ai-file-chip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>${escHtml(a.name || 'File')}</div>`;
      }
    });
  }

  bubble.innerHTML = `
    <div class="${isBot ? 'ai-avatar-bot' : 'ai-avatar-user'}">${isBot ? 'AI' : initials}</div>
    <div class="ai-msg-wrap">
      ${mediaHtml}
      <div class="ai-msg">${formatAiText(text)}</div>
      <div class="ai-time">${nowTime()}</div>
    </div>`;
  body.appendChild(bubble);
  body.scrollTop = body.scrollHeight;
}

export function showAiTyping() {
  const body = document.getElementById('ai-chat-body');
  const el = document.createElement('div');
  el.id = 'ai-typing';
  el.className = 'ai-bubble ai-bubble-bot';
  el.innerHTML = `
    <div class="ai-avatar-bot">AI</div>
    <div class="ai-typing">
      <div class="ai-dot"></div>
      <div class="ai-dot"></div>
      <div class="ai-dot"></div>
    </div>`;
  body.appendChild(el);
  body.scrollTop = body.scrollHeight;
}

export function hideAiTyping() {
  const el = document.getElementById('ai-typing');
  if (el) el.remove();
}

export function renderAiChips() {
  const body = document.getElementById('ai-chat-body');
  const el = document.createElement('div');
  el.className = 'ai-chips';
  el.id = 'ai-chips';
  el.innerHTML = AI_CHIPS.map(c =>
    `<div class="ai-chip" onclick="sendAiMessage('${c.replace(/'/g,"\\'")}')">${c}</div>`
  ).join('');
  body.appendChild(el);
  body.scrollTop = body.scrollHeight;
}

// Attach menu
export function aiToggleAttachMenu() {
  const menu = document.getElementById('ai-attach-menu');
  const btn  = document.getElementById('ai-attach-toggle');
  menu.classList.toggle('open');
  btn.style.color = menu.classList.contains('open') ? '#10b981' : '';
  btn.style.borderColor = menu.classList.contains('open') ? 'rgba(16,185,129,0.4)' : '';
}

export function aiTriggerFile(accept, type) {
  const inp = document.getElementById('ai-file-input');
  inp.accept = accept;
  inp.dataset.fileType = type;
  inp.value = '';
  inp.click();
  document.getElementById('ai-attach-menu').classList.remove('open');
}

export function aiHandleFileSelect(input) {
  const file = input.files[0];
  if (!file) return;
  const type = input.dataset.fileType || 'file';
  const reader = new FileReader();
  reader.onload = function(e) {
    const dataUrl = e.target.result;
    aiPendingAttachments.push({ type, dataUrl, mimeType: file.type, name: file.name });
    renderAttachPreview();
  };
  reader.readAsDataURL(file);
}

export function renderAttachPreview() {
  const strip = document.getElementById('ai-attach-preview');
  strip.innerHTML = '';
  if (aiPendingAttachments.length === 0) {
    strip.classList.remove('has-items');
    return;
  }
  strip.classList.add('has-items');
  aiPendingAttachments.forEach((a, i) => {
    const thumb = document.createElement('div');
    thumb.className = 'ai-attach-thumb';
    if (a.type === 'photo') {
      thumb.innerHTML = `<img src="${a.dataUrl}" alt="">`;
    } else if (a.type === 'video') {
      thumb.innerHTML = `<video src="${a.dataUrl}"></video>`;
    } else {
      thumb.innerHTML = `<div class="ai-attach-type"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg><span>${escHtml(a.name.split('.').pop().toUpperCase())}</span></div>`;
    }
    thumb.innerHTML += `<div class="ai-attach-remove" onclick="aiRemoveAttach(${i})">✕</div>`;
    strip.appendChild(thumb);
  });
}

export function aiRemoveAttach(i) {
  aiPendingAttachments.splice(i, 1);
  renderAttachPreview();
}

export let _aiRequestInFlight = false;

export async function sendAiMessage(presetText) {
  if (_aiRequestInFlight) {
    if (typeof showToast === 'function') showToast('⏳ Still waiting on the previous reply — one sec');
    return;
  }

  const input = document.getElementById('ai-input');
  const text  = (presetText || input.value).trim();
  const attachments = [...aiPendingAttachments];

  if (!text && attachments.length === 0) return;
  input.value = '';
  aiPendingAttachments = [];
  renderAttachPreview();

  // Remove welcome cards and chips
  const cards = document.getElementById('ai-welcome-cards');
  if (cards) cards.remove();
  const chips = document.getElementById('ai-chips');
  if (chips) chips.remove();

  const displayText = text || (attachments.length > 0 ? `[Sent ${attachments.length} file${attachments.length>1?'s':''}]` : '');
  appendAiMessage('user', displayText, attachments);

  // Build message content for API
  const userContent = [];

  // Add images to content
  attachments.forEach(a => {
    if (a.type === 'photo' && a.mimeType.startsWith('image/')) {
      const base64 = a.dataUrl.split(',')[1];
      userContent.push({
        type: 'image',
        source: { type: 'base64', media_type: a.mimeType, data: base64 }
      });
    }
  });

  if (text) {
    userContent.push({ type: 'text', text });
  } else if (attachments.length > 0) {
    const hasImage = attachments.some(a => a.type === 'photo');
    const hasVideo = attachments.some(a => a.type === 'video');
    const prompt = hasImage ? 'Analyze this football image and tell me everything you observe.' : hasVideo ? 'I sent a football video. Describe what kind of football content this likely is and give relevant analysis.' : 'Analyze the attached file in the context of football.';
    userContent.push({ type: 'text', text: prompt });
  }

  aiMessages.push({ role: 'user', content: userContent.length === 1 && userContent[0].type === 'text' ? userContent[0].text : userContent });
  showAiTyping();
  _aiRequestInFlight = true;

  try {
    const res = await fetch('/api/ai', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        max_tokens: 800,
        system: AI_SYSTEM_PROMPT,
        messages: aiMessages,
      })
    });

    const data = await res.json();
    hideAiTyping();

    if (data.content && data.content[0] && data.content[0].text) {
      const reply = data.content[0].text;
      appendAiMessage('bot', reply);
      aiMessages.push({ role: 'assistant', content: reply });

      // Keep history short — resending the WHOLE conversation on every
      // message was the actual cause of "Request Entity Too Large" and
      // rate-limit errors after just a couple of messages. 10 messages
      // (~5 exchanges) is plenty of context without ballooning token count.
      if (aiMessages.length > 10) aiMessages = aiMessages.slice(-10);

      // Strip image data from older messages in history — only the message
      // it was actually sent with needs the real image bytes; carrying full
      // base64 images forward in every subsequent request is what made
      // token/size usage explode fastest of anything in the history.
      aiMessages = aiMessages.map((m, i) => {
        if (i === aiMessages.length - 1) return m; // leave the most recent message untouched
        if (Array.isArray(m.content)) {
          return { ...m, content: m.content.filter(c => c.type !== 'image').map(c => c.type === 'text' ? c : { type: 'text', text: '[image sent earlier]' }) };
        }
        return m;
      });
    } else if (data.error) {
      const errMsg = data.error.message || 'Something went wrong.';
      const friendly = errMsg.includes('x-api-key') || errMsg.includes('api-key') || errMsg.includes('API key') || errMsg.includes('Invalid API Key')
        ? '⚠️ AI service is currently unavailable. The app owner needs to check the Groq API key.'
        : `⚠️ ${errMsg}`;
      appendAiMessage('bot', friendly);
      // A failed request still added a 'user' message to aiMessages above —
      // remove it so the next real request doesn't send two user turns in a
      // row (which is what was corrupting message order and causing more
      // failures downstream).
      if (aiMessages.length && aiMessages[aiMessages.length - 1].role === 'user') aiMessages.pop();
    } else {
      appendAiMessage('bot', "Hmm, I didn't get a response. Please try again! ⚽");
      if (aiMessages.length && aiMessages[aiMessages.length - 1].role === 'user') aiMessages.pop();
    }
  } catch(e) {
    hideAiTyping();
    appendAiMessage('bot', "⚠️ Couldn't connect to AI. Check your connection and try again.");
    if (aiMessages.length && aiMessages[aiMessages.length - 1].role === 'user') aiMessages.pop();
  } finally {
    _aiRequestInFlight = false;
  }
}

// ── Module init (runs once, the first time this module is imported) ──
// aiRemoveAttach is only ever referenced by an onclick this module's own
// renderAttachPreview generates — by the time that HTML exists, this
// module has already loaded, so direct assignment (not a stub) is safe.
window.aiRemoveAttach = aiRemoveAttach;
