name: Daily NPFL Scrape
on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Changed from 18 to 20

      - name: Install Dependencies
        run: npm install axios cheerio firebase-admin

      - name: Run Scraper
        run: node scraper.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
